import os
from dotenv import load_dotenv

load_dotenv()

RABBITMQ_HOST = os.getenv("RABBITMQ_HOST")
RABBITMQ_PORT = int(os.getenv("RABBITMQ_PORT", 5672))
RABBITMQ_USER = os.getenv("RABBITMQ_USER")
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD")

# mail-serivce

MAIL_EXCHANGE = os.getenv("MAIL_EXCHANGE")
EMAIL_VERIFICATION_ROUTING_KEY = os.getenv("EMAIL_VERIFICATION_ROUTING_KEY")
MAIL_QUEUE = os.getenv("MAIL_QUEUE")
MAIL_DLQ = os.getenv("MAIL_DLQ")
USER_RESTORE_ROUTING_KEY = os.getenv("USER_RESTORE_ROUTING_KEY")

# survey-service

USER_EXCHANGE = os.getenv("USER_EXCHANGE")
USER_CREATE_ROUTING_KEY = os.getenv("USER_CREATE_ROUTING_KEY")
USER_DELETE_ROUTING_KEY= os.getenv("USER_DELETE_ROUTING_KEY")
USER_CHANGE_USERNAME_ROUTING_KEY= os.getenv("USER_CHANGE_USERNAME_ROUTING_KEY")
USER_CHANGE_EMAIL_ROUTING_KEY= os.getenv("USER_CHANGE_EMAIL_ROUTING_KEY")
CHANGE_PASSWORD_ROUTING_KEY=os.getenv("CHANGE_PASSWORD_ROUTING_KEY")