filebeat.inputs:
  # ==============================
  # Docker container logs
  # ==============================
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    json.message_key: message   
    json.keys_under_root: true
    json.add_error_key: true
    processors:
      - add_docker_metadata: {}  

output.logstash:
  hosts: ["logstash:5044"]
  ssl.enabled: false


logging.level: info
logging.to_files: false
logging.to_syslog: false