input {
  beats {
    port => 5044
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    data_stream => true
    data_stream_type => "logs"
    data_stream_dataset => "%{[service][name]}"
    data_stream_namespace => "default"
    ecs_compatibility => v8
  }

  stdout { codec => rubydebug }
}