input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    data_stream => "true"
    data_stream_type => "logs"
    data_stream_dataset => "reforma.all"
    data_stream_namespace => "default"
    ecs_compatibility => v8
  }

  stdout {
    codec => rubydebug
  }
}