input {
  tcp {
    port => 5000
    codec => json_lines   
  }
}

filter {
  if [log] {
    if ![service] and [log][service] {
      mutate { add_field => { "service" => "%{[log][service]}" } }
    }

    if [log][context] {
      mutate { add_field => { "context" => "%{[log][context]}" } }
    }

    if [log][trace_id] {
      mutate { add_field => { "trace_id" => "%{[log][trace_id]}" } }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "reforma-%{[service]}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}