networks:
  backend:
    driver: bridge

volumes:
  report_pgdata:
  survey_pgdata:
  auth_pgdata:
  payment_pgdata:
  rabbitmq_data:
  rabbitmq_log:
  grafana-data:
  seaweed_pgdata:
  master1_data:
  master2_data:
  master3_data:
  volume1_data:
  volume2_data:
  volume3_data:

services:

  # ===============================
  # MICROSERVICE
  # ===============================
  auth_service:
    build:
      context: ..
      dockerfile: reforma_authorization/Dockerfile
    container_name: reforma_authorization
    restart: always
    env_file:
      - ../reforma_authorization/.env
    ports:
      - "8000:8000"
    depends_on:
      - auth_postgres
      - rabbitmq
    networks:
      - backend

  mail_service:
    build:
      context: ..
      dockerfile: reforma_mail/Dockerfile
    container_name: reforma_mail
    restart: always
    env_file:
      - ../reforma_mail/.env
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
    networks:
      - backend

  survey_service:
    build:
      context: ..
      dockerfile: reforma_survey/Dockerfile
    container_name: reforma_survey
    restart: always
    env_file:
      - ../reforma_survey/.env
    ports:
      - "8002:8000"
    depends_on:
      - survey_postgres
      - rabbitmq
    networks:
      - backend

  payment_service:
    build:
      context: ..
      dockerfile: reforma_payment/Dockerfile
    container_name: reforma_payment
    restart: always
    env_file:
      - ../reforma_payment/.env
    ports:
      - "8003:8000"
    depends_on:
      - payment_postgres
      - rabbitmq
    networks:
      - backend

  report_service:
    build:
      context: ..
      dockerfile: reforma_report/Dockerfile
    container_name: reforma_report
    restart: always
    env_file:
      - ../reforma_report/.env
    ports:
      - "8004:8000"
    depends_on:
      - report_postgres
      - rabbitmq
    networks:
      - backend

  # ===============================
  # POSTGRESQL
  # ===============================
  auth_postgres:
    image: postgres:15
    container_name: postgres_authorization_db
    restart: always
    environment:
      POSTGRES_USER: reforma_authorization_user
      POSTGRES_PASSWORD: reforma_authorization_pass
      POSTGRES_DB: reforma_authorization_db
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reforma_authorization_user -d reforma_authorization_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  survey_postgres:
    image: postgres:15
    container_name: postgres_survey_db
    restart: always
    environment:
      POSTGRES_USER: reforma_survey_user
      POSTGRES_PASSWORD: reforma_survey_pass
      POSTGRES_DB: reforma_survey_db
    ports:
      - "5433:5432"
    volumes:
      - survey_pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reforma_survey_user -d reforma_survey_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  report_postgres:
    image: postgres:15
    container_name: postgres_report_db
    restart: always
    environment:
      POSTGRES_USER: reforma_report_user
      POSTGRES_PASSWORD: reforma_report_pass
      POSTGRES_DB: reforma_report_db
    ports:
      - "5434:5432"
    volumes:
      - report_pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reforma_report_user -d reforma_report_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  payment_postgres:
    image: postgres:15
    container_name: postgres_payment_db
    restart: always
    environment:
      POSTGRES_USER: reforma_payment_user
      POSTGRES_PASSWORD: reforma_payment_pass
      POSTGRES_DB: reforma_payment_db
    ports:
      - "5435:5432"
    volumes:
      - payment_pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reforma_payment_user -d reforma_payment_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  seaweed_postgres:
    image: postgres:15
    container_name: postgres_seaweed_db
    environment:
      POSTGRES_DB: seaweedfs
      POSTGRES_USER: seaweed
      POSTGRES_PASSWORD: seaweedpass
    ports:
      - "5436:5432"
    volumes:
      - seaweed_pgdata:/var/lib/postgresql/data
    networks:
      - backend

  # ===============================
  # RABBITMQ
  # ===============================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    mem_limit: 4g
    mem_reservation: 1g

  # ===============================
  # ELK Stack
  # ===============================

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.9.0
    container_name: filebeat
    user: root
    command: ["--strict.perms=false"]
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - logstash
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      SERVER_BASEPATH: "/kibana"
      SERVER_REWRITEBASEPATH: "true"
    ports:
      - "5601:5601"
    networks:
      - backend

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - backend

  # ===============================
  # NGINX Gateway
  # ===============================
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ../reforma_gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - auth_service
      - mail_service
      - survey_service
      - payment_service
      - report_service
      - kibana
    restart: unless-stopped
    networks:
      - backend

  # ===============================
  # SEAWEEDFS
  # ===============================
  # ================= MASTER CLUSTER =================

  master1:
    image: chrislusf/seaweedfs:3.68
    command: >
      master
      -ip=master1
      -ip.bind=0.0.0.0
      -mdir=/data
      -peers=master1:9333,master2:9333,master3:9333
      -defaultReplication=010
    volumes:
      - master1_data:/data
    ports:
      - "9333:9333"
    networks:
      - backend

  master2:
    image: chrislusf/seaweedfs:3.68
    command: >
      master
      -ip=master2
      -ip.bind=0.0.0.0
      -mdir=/data
      -peers=master1:9333,master2:9333,master3:9333
      -defaultReplication=010
    volumes:
      - master2_data:/data
    networks:
      - backend

  master3:
    image: chrislusf/seaweedfs:3.68
    command: >
      master
      -ip=master3
      -ip.bind=0.0.0.0
      -mdir=/data
      -peers=master1:9333,master2:9333,master3:9333
      -defaultReplication=010
    volumes:
      - master3_data:/data
    networks:
      - backend

  # ================= VOLUME SERVERS =================

  volume1:
    image: chrislusf/seaweedfs:3.68
    command: >
      volume
      -mserver=master1:9333,master2:9333,master3:9333
      -dir=/data
      -dataCenter=dc1
      -rack=rack1
    volumes:
      - volume1_data:/data
    networks:
      - backend

  volume2:
    image: chrislusf/seaweedfs:3.68
    command: >
      volume
      -mserver=master1:9333,master2:9333,master3:9333
      -dir=/data
      -dataCenter=dc1
      -rack=rack2
    volumes:
      - volume2_data:/data
    networks:
      - backend

  volume3:
    image: chrislusf/seaweedfs:3.68
    command: >
      volume
      -mserver=master1:9333,master2:9333,master3:9333
      -dir=/data
      -dataCenter=dc1
      -rack=rack3
    volumes:
      - volume3_data:/data
    networks:
      - backend

  # ================= FILER =================

  filer:
    image: chrislusf/seaweedfs:3.68
    command: >
      filer
      -master=master1:9333,master2:9333,master3:9333
    volumes:
      - ./config/filer.toml:/etc/seaweedfs/filer.toml:ro
    depends_on:
      - master1
      - seaweed_postgres
    ports:
      - "8888:8888"
    networks:
      - backend

  # ================= S3 GATEWAY =================

  s3:
    image: chrislusf/seaweedfs:latest
    command: >
      s3
      -filer=filer:8888
      -config=/etc/seaweedfs/s3.json
    volumes:
      - ./config/s3.json:/etc/seaweedfs/s3.json:ro
    ports:
      - "8333:8333"
    depends_on:
      - filer
    networks:
      - backend

  s3-init:
    image: python:3.12-slim
    depends_on:
      - s3
    networks:
      - backend
    command: >
      sh -c "
        pip install --no-cache-dir awscli &&
        echo 'Ждём S3...' &&
        for i in {1..30}; do
          curl -s -f http://s3:8333 >/dev/null && break;
          sleep 4;
        done &&
        aws --endpoint-url http://s3:8333 s3 mb s3://reforma-media ||
        echo 'Бакет уже существует или ошибка, продолжаем...';
      "
    environment:
      - AWS_ACCESS_KEY_ID=ADMINACCESSKEY
      - AWS_SECRET_ACCESS_KEY=AdminSuperSecretKey123456789
      - AWS_DEFAULT_REGION=us-east-1