import os
from dotenv import load_dotenv

load_dotenv()

# main settings

RABBITMQ_HOST = os.getenv("RABBITMQ_HOST")
RABBITMQ_PORT = int(os.getenv("RABBITMQ_PORT", 5672))
RABBITMQ_USER = os.getenv("RABBITMQ_USER")
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD")

# survey-service

USER_EXCHANGE = os.getenv("USER_EXCHANGE")

USER_CREATE_ROUTING_KEY = os.getenv("USER_CREATE_ROUTING_KEY")
USER_DELETE_ROUTING_KEY = os.getenv("USER_DELETE_ROUTING_KEY")
USER_CHANGE_USERNAME_ROUTING_KEY = os.getenv("USER_CHANGE_USERNAME_ROUTING_KEY")
USER_CHANGE_EMAIL_ROUTING_KEY = os.getenv("USER_CHANGE_EMAIL_ROUTING_KEY")

# with reforma_report

REPORT_EXCHANGE = os.getenv("REPORT_EXCHANGE")
RESPONSE_SUBMITTED_ROUTING_KEY = os.getenv("RESPONSE_SUBMITTED_ROUTING_KEY")
REPORT_GENERATION_ROUTING_KEY = os.getenv("REPORT_GENERATION_ROUTING_KEY")

# with payment

ADD_BALANCE_ROUTING_KEY = os.getenv("ADD_BALANCE_ROUTING_KEY")

# with report

GET_ANSWERS_FOR_QUESTION_ROUTING_KEY = os.getenv("GET_ANSWERS_FOR_QUESTION_ROUTING_KEY")
SENTIMENT_REQUEST_ROUTING_KEY=os.getenv("SENTIMENT_REQUEST_ROUTING_KEY")

# with model

MODEL_EXCHANGE= os.getenv("MODEL_EXCHANGE")
SENTIMENT_BATCH_ANSWERS_ROUTING_KEY=os.getenv("SENTIMENT_BATCH_ANSWERS_ROUTING_KEY")
