import os
from dotenv import load_dotenv

load_dotenv()

# main settings

RABBITMQ_HOST = os.getenv("RABBITMQ_HOST")
RABBITMQ_PORT = int(os.getenv("RABBITMQ_PORT", 5672))
RABBITMQ_USER = os.getenv("RABBITMQ_USER")
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD")

# survey-service

USER_EXCHANGE = os.getenv("USER_EXCHANGE")

USER_CREATE_ROUTING_KEY = os.getenv("USER_CREATE_ROUTING_KEY")
USER_DELETE_ROUTING_KEY = os.getenv("USER_DELETE_ROUTING_KEY")
USER_CHANGE_USERNAME_ROUTING_KEY = os.getenv("USER_CHANGE_USERNAME_ROUTING_KEY")
USER_CHANGE_EMAIL_ROUTING_KEY = os.getenv("USER_CHANGE_EMAIL_ROUTING_KEY")
REPORT_EXCHANGE = os.getenv("REPORT_EXCHANGE")
REPORT_GENERATION_ROUTING_KEY = os.getenv("REPORT_GENERATION_ROUTING_KEY")

# with payment

ADD_BALANCE_ROUTING_KEY = os.getenv("ADD_BALANCE_ROUTING_KEY")
