import os
from dotenv import load_dotenv

load_dotenv()

RABBITMQ_HOST = os.getenv("RABBITMQ_HOST")
RABBITMQ_PORT = int(os.getenv("RABBITMQ_PORT", 5672))
RABBITMQ_USER = os.getenv("RABBITMQ_USER")
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD")

# survay-service

USER_EXCHANGE = os.getenv("USER_EXCHANGE")
USER_CREATE_ROUTING_KEY = os.getenv("USER_CREATE_ROUTING_KEY")
USER_DELETE_ROUTING_KEY= os.getenv("USER_DELETE_ROUTING_KEY")
USER_CHANGE_USERNAME_ROUTING_KEY= os.getenv("USER_CHANGE_USERNAME_ROUTING_KEY")
USER_CHANGE_EMAIL_ROUTING_KEY= os.getenv("USER_CHANGE_EMAIL_ROUTING_KEY")